---
apiVersion: v1
kind: Namespace
metadata:
  name: "openshift-compliance"
  annotations:
    openshift.io/display-name: OpenShift Compliance Operator
  labels:
    openshift.io/cluster-monitoring: "true"
