default:
  application:
    enabled: false
    destination:
      server: https://kubernetes.default.svc
      namespace: "openshift-gitops"
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      retry: {}
      syncOptions: []

projects:
  &prj-cluster-apps cluster-config:
    namespace: &ns-gitops openshift-gitops
    additionalLabels: {}
    additionalAnnotations: {}
    permitOnlyProjectScopedClusters: false
    description: This project is for cluster-wide applications
    sourceRepos:
      - https://github.com/k8scope/rh-gitops-helm.git
      - https://prometheus-community.github.io/helm-charts
    destinations:
      - namespace: "*"
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    clusterResourceBlacklist: []
    namespaceResourceBlacklist: []
    namespaceResourceWhitelist: []
    orphanedResources: {}
    roles: []
    syncWindows: []
    signatureKeys: []
    sourceNamespaces: []

applications:
  monitoring:
    enabled: true
    namespace: *ns-gitops
    project: *prj-cluster-apps
    sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 70.4.1
      chart: kube-prometheus-stack
      helm:
        releaseName: monitoring
        ignoreMissingValueFiles: true
        valueFiles:
          - $values/datacenters/monitoring.yaml
          - $values/datacenters/dc01/monitoring.yaml
          - $values/datacenters/dc01/production/monitoring.yaml
          - $values/datacenters/dc01/production/prd01/monitoring.yaml
    - repoURL: https://github.com/k8scope/rh-gitops-helm.git
      targetRevision: HEAD
      ref: values

  compliance-operator:
    enabled: true
    namespace: *ns-gitops
    project: *prj-cluster-apps
    sources:
    - repoURL: https://github.com/k8scope/rh-helm-charts
      targetRevision: 0.1.0
      chart: compliance-operator
      helm:
        releaseName: compliance-operator
        ignoreMissingValueFiles: true
        valueFiles:
          - $values/datacenters/compliance-operator.yaml
          - $values/datacenters/dc01/compliance-operator.yaml
          - $values/datacenters/dc01/production/compliance-operator.yaml
          - $values/datacenters/dc01/production/prd01/compliance-operator.yaml
    - repoURL: https://github.com/k8scope/rh-gitops-helm.git
      targetRevision: HEAD
      ref: values
