# Default values for argocd-app-of-apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# appSuffix is the suffix to append to the app name
# This will be applied to all applications in the app-of-apps, unless the application has skipGlobalSuffix set to true
appSuffix: null

# appSourceBasePath is the base path for the application source
# This will be applied to all applications in the app-of-apps, unless the application has source.ignoreBasePath set to true
# If source.ignoreBasePath is set to false (default), the source.path will be appended to the appSourceBasePath
appSourceBasePath: null

# -- Default values for all applications
default:
  # -- Define default configurations for all applications
  # -- We expect the same structure as for the applications below
  application:
    enabled: false
    annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true
    source:
      # -- Allows to ignore the base path set in appSourceBasePath
      ignoreBasePath: false
      # -- The path to the application source
      # This will be appended to the appSourceBasePath if ignoreBasePath is false
      # If ignoreBasePath is true, this will be the full path to the application source
      path: ""
      # -- The URL to the application source repository (e.g. https://github.com/example/example.git)
      repoURL: ""
      # -- The revision of the application source repository
      # This can be a branch, tag, or commit SHA
      targetRevision: HEAD
    sources:
      - repoURL: ""
        targetRevision: HEAD
        ref: ""


# -- Define a map of projects and their configurations
projects: {}
  # myProject:
    # annotations: {}
    # description:
    # namespace:
    # sourceRepos: []
    # destinations:
    #   - namespace: '*'
    #     server: https://kubernetes.default.svc
    # extraFields: |
    #   clusterResourceWhitelist:
    #   - group: '*'
    #     kind: '*'

# -- Define a map of applications and their configurations
applications:
  myApp1:
    # applications.<app-name>.enabled -- enabled is a flag to enable or disable the application
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: "14"
    # applications.<app-name>.syncPolicy -- syncPolicy is the sync policy for the application
    syncPolicy:
      # applications.<app-name>.syncPolicy.automated -- automated is the automated sync policy for the application
      automated:
        # applications.<app-name>.syncPolicy.automated.selfHeal -- selfHeal is a flag to enable or disable self-healing
        selfHeal: true
        # applications.<app-name>.syncPolicy.automated.prune -- prune is a flag to enable or disable pruning
        prune: true
      # applications.<app-name>.syncPolicy.retry -- retry is the retry strategy for the application
      retry: {}
      # applications.<app-name>.syncPolicy.syncOptions -- syncOptions is a list of sync options
      syncOptions: []
    source:
      # applications.<app-name>.source.repoURL -- repoURL is the URL to the application source repository
      repoURL: https://github.com/my-org/my-repo  # path is missing so no manifests are generated
      # applications.<app-name>.source.targetRevision -- targetRevision is the revision of the application source repository
      targetRevision: master
      # applications.<app-name>.source.ignoreBasePath -- ignoreBasePath is a flag to ignore the base path set in appSourceBasePath
      ignoreBasePath: false
      # applications.<app-name>.source.path -- path is the path to the application source
      path: ""
      # applications.<app-name>.source.helm -- helm is the Helm specific configuration
      # For more information about the Helm configuration, see https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm
      helm:
        # applications.<app-name>.source.helm.releaseName -- releaseName is the name of the Helm release
        releaseName: ""
        # applications.<app-name>.source.helm.ignoreMissingValueFiles -- ignoreMissingValueFiles is a flag to ignore missing value files
        ignoreMissingValueFiles: false
        # applications.<app-name>.source.helm.valueFiles -- valueFiles is a list of Helm value files to be used (`$ref` can be used to reference a different source)
        valueFiles:
          - $myRepo/values.yaml
    sources:
    - # applications.<app-name>.sources.0.repoURL -- repoURL is the URL to the application source repository
      repoURL: https://github.com/my-org/my-repo  # path is missing so no manifests are generated
      # applications.<app-name>.sources.0.targetRevision -- targetRevision is the revision of the application source repository
      targetRevision: master
      # applications.<app-name>.sources.0.ignoreBasePath -- ignoreBasePath is a flag to ignore the base path set in appSourceBasePath
      ignoreBasePath: false
      # applications.<app-name>.sources.0.path -- path is the path to the application source
      path: ""
      # applications.<app-name>.sources.0.ref -- ref is the reference name to be used in the application (only used when Helm is used with different repositories for chart and values)
      ref: myRepo
      # applications.<app-name>.sources.0.helm -- helm is the Helm specific configuration
      # For more information about the Helm configuration, see https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm
      helm:
        # applications.<app-name>.sources.0.helm.releaseName -- releaseName is the name of the Helm release
        releaseName: ""
        # applications.<app-name>.sources.0.helm.ignoreMissingValueFiles -- ignoreMissingValueFiles is a flag to ignore missing value files
        ignoreMissingValueFiles: false
        # applications.<app-name>.sources.0.helm.valueFiles -- valueFiles is a list of Helm value files to be used (`$ref` can be used to reference a different source)
        valueFiles:
          - $myRepo/values.yaml
    extraFields: {}
