name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run chart-releaser
        uses: k8scope/helm-chart-releaser-action@v1.0.0
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          chart_repository_url: oci://ghcr.io/k8scope/rh-helm-charts
          chart_repository_username: ${{ github.actor }}
          chart_repository_password: ${{ secrets.GITHUB_TOKEN }}
